web:
  build: ../simple_rack
  restart: always
  command: unicorn -c config/unicorn.rb
  environment:
    RACK_ENV: development
    WEB_CONCURRENCY: 2
    VIRTUAL_HOST: simple_rack
  expose:
    - 8080

nginx:
  image: nginx
  container_name: simple_rack_nginx
  restart: always
  ports:
    - 80:80
  volumes:
    - ./tmp/nginx:/etc/nginx/conf.d
    - ./logs:/var/log/nginx

nginx-gen:
  image: jwilder/docker-gen
  restart: always
  volumes_from:
    - nginx
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./templates:/etc/docker-gen/templates:ro
  command: "-notify-sighup simple_rack_nginx -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
